// Language builtins filtered from call-edge resolution.
// Ported from upstream graphify v8 extractors/base.py
// (_LANGUAGE_BUILTIN_GLOBALS): calls to language builtins and prelude types
// (String, Promise, str, print, Some, Vec...) otherwise resolve to bare-name
// stub nodes that merge corpus-wide and become meaningless god nodes.

/// Conservative per-language builtin/global names. Only names that are
/// essentially never user-defined call targets in that language.
fn builtin_set(language: &str) -> &[&str] {
    match language {
        "Python" => &[
            "print",
            "len",
            "range",
            "str",
            "int",
            "float",
            "bool",
            "list",
            "dict",
            "set",
            "tuple",
            "type",
            "isinstance",
            "issubclass",
            "super",
            "open",
            "enumerate",
            "zip",
            "map",
            "filter",
            "sorted",
            "reversed",
            "min",
            "max",
            "sum",
            "abs",
            "round",
            "repr",
            "input",
            "format",
            "getattr",
            "setattr",
            "hasattr",
            "callable",
            "hash",
            "id",
            "iter",
            "next",
            "vars",
            "dir",
            "bytes",
            "bytearray",
            "frozenset",
            "complex",
            "NotImplemented",
            "Ellipsis",
        ],
        "JavaScript" | "TypeScript" => &[
            "String",
            "Number",
            "Boolean",
            "Array",
            "Object",
            "JSON",
            "Math",
            "Date",
            "Promise",
            "Map",
            "Set",
            "WeakMap",
            "WeakSet",
            "Symbol",
            "BigInt",
            "console",
            "Error",
            "TypeError",
            "RangeError",
            "SyntaxError",
            "RegExp",
            "parseInt",
            "parseFloat",
            "isNaN",
            "isFinite",
            "encodeURIComponent",
            "decodeURIComponent",
            "setTimeout",
            "setInterval",
            "clearTimeout",
            "clearInterval",
            "fetch",
            "require",
            "queueMicrotask",
            "structuredClone",
            "alert",
            "window",
            "document",
            "globalThis",
        ],
        "Rust" => &[
            "Some",
            "None",
            "Ok",
            "Err",
            "String",
            "Vec",
            "Option",
            "Result",
            "Box",
            "Rc",
            "Arc",
            "RefCell",
            "Cell",
            "HashMap",
            "HashSet",
            "BTreeMap",
            "BTreeSet",
            "Cow",
            "println",
            "print",
            "eprintln",
            "eprint",
            "format",
            "vec",
            "panic",
            "assert",
            "assert_eq",
            "assert_ne",
            "debug_assert",
            "debug_assert_eq",
            "todo",
            "unimplemented",
            "unreachable",
            "write",
            "writeln",
            "dbg",
            "default",
            "from",
            "into",
            "try_from",
            "try_into",
            "clone",
            "to_string",
            "to_owned",
            "len",
            "is_empty",
            "iter",
            "into_iter",
            "unwrap",
            "unwrap_or",
            "unwrap_or_else",
            "expect",
            "map",
            "filter",
            "collect",
            "push",
            "pop",
            "as_str",
            "new",
        ],
        "Go" => &[
            "len", "cap", "make", "new", "append", "copy", "delete", "panic", "recover", "print",
            "println", "close", "complex", "real", "imag", "min", "max", "clear",
        ],
        "Java" => &[
            "System",
            "String",
            "Integer",
            "Double",
            "Boolean",
            "Character",
            "Math",
            "Object",
            "List",
            "Map",
            "Set",
            "ArrayList",
            "HashMap",
            "HashSet",
            "Optional",
            "println",
            "print",
            "printf",
            "toString",
            "equals",
            "hashCode",
            "getClass",
        ],
        "C#" => &[
            "Console",
            "String",
            "Int32",
            "Int64",
            "Double",
            "Boolean",
            "Math",
            "Object",
            "List",
            "Dictionary",
            "Task",
            "Convert",
            "Write",
            "WriteLine",
            "ReadLine",
            "ToString",
            "GetHashCode",
            "GetType",
            "Equals",
        ],
        "Ruby" => &[
            "puts",
            "print",
            "p",
            "pp",
            "require",
            "require_relative",
            "lambda",
            "proc",
            "raise",
            "loop",
            "sleep",
            "format",
            "sprintf",
            "gets",
            "Array",
            "Hash",
            "String",
            "Integer",
            "Float",
            "Struct",
            "new",
        ],
        _ => &[],
    }
}

/// True if `name` is a builtin/global of `language` and should not produce a
/// call edge. Case-sensitive for capitalized type names, exact match only.
pub fn is_language_builtin(name: &str, language: &str) -> bool {
    builtin_set(language).contains(&name)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn filters_python_builtins() {
        assert!(is_language_builtin("print", "Python"));
        assert!(is_language_builtin("enumerate", "Python"));
        assert!(!is_language_builtin("my_func", "Python"));
        // case-sensitive: Print is not the builtin
        assert!(!is_language_builtin("Print", "Python"));
    }

    #[test]
    fn filters_js_globals() {
        assert!(is_language_builtin("Promise", "JavaScript"));
        assert!(is_language_builtin("console", "TypeScript"));
        assert!(!is_language_builtin("Promise", "Python"));
    }

    #[test]
    fn unknown_language_filters_nothing() {
        assert!(!is_language_builtin("print", "Zig"));
    }
}
